### ISSUE TITLE
Suggestion: css animation

### ISSUE THREAD

**Issue by kirillgroshkov** [hilongjw/vue-progressbar#69]
Works so much better with:

```css
.__cov-progress {
  transition: all .3s ease-in-out;
}
```
